FROM nginx
MAINTAINER lujinbo <lujinbo@danke.com>
RUN echo '<h1>Hello Docker!</h1>' > /usr/share/nginx/html/index.html
#RUN echo "deb http://mirrors.aliyun.com/kali kali-rolling main non-free contrib" > /etc/apt/sources.listecho "deb-src http://mirrors.aliyun.com/kali kali-rolling main non-free contrib" >> /etc/apt/sources.listecho "deb http://mirrors.aliyun.com/kali-security kali-rolling/updates main contrib non-free" >> /etc/apt/sources.list

RUN apt-get update &&  apt-get install -y curl
# 健康检查 --interval检查的间隔 超时timeout retries失败次数
#HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
#    CMD curl --fail http://dk-php-fpm:9000 || exit 1
#EXPOSE 9090
